#!/bin/sh

mkdir -p /usr/local/bin

ln -s -f /opt/apps/com.gitee.deepin-opensource.desktop-entry-editor/files/bin/desktop-entry-editor /usr/local/bin/desktop-entry-editor

ln -s -f ../../opt/apps/com.gitee.deepin-opensource.desktop-entry-editor/files/share/desktop-entry-editor /usr/share/

update-icon-caches /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true
update-mime-database /usr/share/mime || true
